# Generated by Django 5.0.2 on 2024-04-24 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publish', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFavouriteArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ex00_favourite_articles', to='publish.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ex00_favourite_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
