# Generated by Django 5.0.2 on 2024-04-23 09:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_tip_downvote_tip_upvote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tip',
            name='downvote',
        ),
        migrations.RemoveField(
            model_name='tip',
            name='upvote',
        ),
        migrations.AddField(
            model_name='tip',
            name='downvoters',
            field=models.ManyToManyField(blank=True, related_name='downvoted_tips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tip',
            name='upvoters',
            field=models.ManyToManyField(blank=True, related_name='upvoted_tips', to=settings.AUTH_USER_MODEL),
        ),
    ]
