# Generated by Django 5.0.2 on 2024-04-23 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_date_tip_date_posted_remove_tip_downvoters_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tip',
            old_name='date_posted',
            new_name='date',
        ),
    ]
