# Generated by Django 5.0.2 on 2024-04-24 14:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_tip_can_delete'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='can_downvote',
            field=models.ManyToManyField(blank=True, related_name='can_downvote_tips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tip',
            name='rep_points',
            field=models.IntegerField(default=0),
        ),
    ]
