version: '3.8'

services:
  app:
    build:
      context: FE
      dockerfile: Dockerfile
    networks:
      - matcha
    env_file:
      - ./FE/.env
    init: true
    ports:
      - 5173:5173
    expose:
      - 5173


  db:
    image: postgres:16.2-alpine
    user: "postgres"
    command: postgres -c 'hba_file=/var/lib/postgresql/pg_hba.conf'
    volumes:
      - ./postgresql/pg_hba.conf:/var/lib/postgresql/pg_hba.conf
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    init: true
    healthcheck:
      interval: 5s
      test:
        [
          "CMD-SHELL",
          "pg_isready",
          "-d",
          "$${POSTGRES_DB}",
          "-U",
          "$${POSTGRES_USER}",
        ]
    ports:
      - 5432:5432
    expose:
      - 5432
    networks:
      - matcha

  pgadmin4:
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - 5050:80
    init : true
    depends_on:
      - db
    volumes:
      - ./pgadmin_servers.json:/pgadmin4/servers.json
    networks:
      - matcha
    
  web:
    build: ./BE
    command: npm run dev
    volumes:
      - ./BE:/BE
    ports:
      - 3000:3000
      - 3001:3001
    env_file:
      - ./BE/.env
    depends_on:
      db:
        condition: service_healthy
    init: true
    networks:
      - matcha

networks:
  matcha:
    driver: bridge

volumes:
  postgres_data:
  static_volume:
  media_volume:
  pgadmin_data: